version: "3.4"

services:
  backend:
    container_name: register-step_backend
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    networks:
      - register-steps

  postgres:
    image: postgres:15
    container_name: register-step_postgres
    restart: unless-stopped
    ports:
      - 6500:5432
    volumes:
      - postgres-register-steps__vol:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - register-steps

  pgAdmin:
    image: dpage/pgadmin4
    container_name: register-step_pgAdmin
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - register-steps

  redis:
    image: redis
    container_name: register-step_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - register-steps

networks:
  register-steps:
    name: register-steps__network
    driver: "bridge"

volumes:
  postgres-register-steps__vol:
    driver: local
