#!/bin/sh

echo "START COMMIT... \n"
echo "The tests will run.\n"

TEST=$(go test ./... | grep "FAIL:")

if ["$TEST" = ""]; then
    printf "COMMIT SUCCEEDED. \n"
    exit 0
else
    printf "\nTests fail, RUN: 'sh ./scripts/tests.sh' - for run the tests... \n"
    printf "\nCOMMIT FAILED!!! \n"
    exit 1
fi